### ISSUE TITLE
Safari now supports lookbehind assertions

### ISSUE THREAD

**Issue by luis-f-lins** [keithamus/eslint-plugin-escompat#20]
Safari started supporting lookbehind assertions starting in version 16.4.

<img width="491" alt="image" src="https://github.com/keithamus/eslint-plugin-escompat/assets/16650877/95f90022-9342-46e2-b0dc-74aafc10ae1b">

I've tried to create a PR to fix `lib/index.js` but the repo won't let me create a new branch in remote.

**Comment by keithamus** [comment]
PRs welcome!
