### ISSUE TITLE
Support for ESLint's new (flat) config file available in v8.21+

### ISSUE THREAD

**Issue by u01jmg3** [keithamus/eslint-plugin-escompat#23]
- https://eslint.org/blog/2022/08/new-config-system-part-1/
- https://eslint.org/blog/2022/08/new-config-system-part-2/

**Comment by keithamus** [comment]
Sounds like a good PR for anyone who would like to make one

**Comment by u01jmg3** [comment]
In the meantime, could we make use of [`@eslint/compat`](https://www.npmjs.com/package/@eslint/compat)? Maybe an example in your README?

**Comment by u01jmg3** [comment]
Quick note: flat config file compatibility could be developed in the first instance with full v9 compatibility coming later as [`@eslint/compat`](https://www.npmjs.com/package/@eslint/compat) could be used in the interim.

This is the approach [`eslint-plugin-compat`](https://github.com/amilajack/eslint-plugin-compat/issues/614) has taken.
