### ISSUE TITLE
Recent features

### ISSUE THREAD

**Issue by brettz9** [keithamus/eslint-plugin-escompat#25]
I see the recommended config sets `ecmaVersion` to 2020.

Is that because there is no detection of features above 2020 (i.e.., for 2021, ~~private methods and accessors, numeric separators~~, logical assignment operators; for 2022, top-level await; ~~public/private, static/instance fields~~; ~~static initialization blocks~~; for 2023, hashbang grammar)?

Might these be tracked here if so?

Thanks!

**Comment by keithamus** [comment]
These should definitely be implemented as lints for this library! I haven't had much time to work on this plugin, though. If you'd be interested in making some PR's I'd be very happy to review+merge, and also offer guidance where I can.

**Comment by brettz9** [comment]
Have my plate full atm, but would be nice to have an issue to be kept updated in case others may be able to assist at some point.

**Comment by brettz9** [comment]
If you could first complete the review of the ESLint 9 PR, I can submit a PR for logical assignment expressions and another updating some of the docs. It seems you actually had a number of the items I misread as missing (now updated above).

**Comment by brettz9** [comment]
Thanks for all the reviews!

**Comment by keithamus** [comment]
Thanks for making the PRs!
